### ISSUE TITLE
✅ [3-4] Gioco Perudo

### ISSUE THREAD

**Issue by Helias** [UNICT-Quality-Development/qd-projects#19]
Simulare il gioco del Perudo, descrizione https://it.wikipedia.org/wiki/Perudo

---

Il progetto dovrà prevedere una pipeline tramite le GitHub Action e lo sviluppo di unit-test mediante il framework pytest raggiungendo una code coverage del 75%.

---

Questo progetto non è ancora stato assegnato a nessuno studente, se sei interessato, commenta questa issue scrivendo almeno 3 username di GitHub (il tuo incluso).

**Comment by Lupix111** [comment]
@Lupix111, @filippocampo98, @Angelo1001, @MassimoBelfioreCode

**Comment by campofilippo98** [comment]
@campofilippo98 (nuovo account GitHub)
