### ISSUE TITLE
✅ [4] MovieAdvisor

### ISSUE THREAD

**Issue by SalvoScavo** [UNICT-Quality-Development/qd-projects#21]
Il progetto consiste nella realizzazione di un software in Python che sia in grado di consigliare la visione di film sulla base delle preferenze di ogni utente.

Il software sarà basato su due funzioni principali:

1. Consigliare a due utenti differenti un film che sia adatto alle preferenze specificate da ognuno (quindi che abbia in comune più preferenze possibili selezionate dai due utenti).

2. Consigliare ad ogni singolo utente film coerenti con la cronologia dei film visionati in precedenza, aggiornandoli in caso le preferenze cambino nel corso delle diverse visioni.

Verrà utilizzato un database pubblico (o API pubblica online) di film con relativa specifica di attributi quali genere, durata e trama.

Il sistema sarà in grado di calcolare la similarità tra film e di registrare le preferenze di ogni utente.

(Es: eseguito il software, un nuovo utente potrà registrare le proprie preferenze interagendo con l'interfaccia grafica che mostrerà una lista di diversi generi e relative domande per poter registrare i gusti dell'utente.
Mentre un utente già registrato avrà elencati differenti categorie di film tra cui una specifica basata sui suoi interessi)                                                   Progetto assegnato a : @SalvoScavo  @Davide496 @Victini378 @andrea-dibartolo

**Comment by andrea-dibartolo** [comment]
Ciao, vorrei partecipare anch'io al progetto.

**Comment by Helias** [comment]
@makapx revisionerà il codice che scriverete e vi supporterà al livello tecnico quando necessario. aggiungetela alla repository e scrivete il link della repository nella descrizione della issue, potete contattare [@makapx](https://t.me/makapx) anche su telegram.

P.S. aggiungete @andrea-dibartolo nella descrizione del progetto dato che è stato aggiunto al team.
