### ISSUE TITLE
🤝 Botquake

### ISSUE THREAD

**Issue by linuchs** [UNICT-Quality-Development/qd-projects#36]
**Progetto relativo al corso di Quality Development
tenuto dal Dott. Stefano Borzi
presso il Dipartimento di Matematica e Informatica dell’Università degli Studi di Catania**

**Cosa ci proponiamo di realizzare: Botquake.**
Ciò che si intende realizzare è un BOT per Telegram, in linguaggio Python, ovvero una applicazione eseguita sulla nostra macchina server, la quale estenderà le funzionalità del server di Telegram, quest’ultimo sarà oggetto di interrogazione da parte dell’utente che potrà inviare comandi mediante l'interfaccia di chat messa a disposizione dal client di Telegram.
Il comando sarà reindirizzato alla nostra macchina che darà risposta tramite il server Telegram al client dal quale l'Utente ha inviato il comando.

**Specifiche dell'applicazione Botquake.**
L'applicazione elaborerà i dati forniti sul sito https://terremoti.ingv.it/ dall'Ingv. 
I dati sono distribuiti sotto licenza Creative Commons Attribution 4.0 international,
https://creativecommons.org/licenses/by/4.0/.
I dati fanno parte di un database di eventi relativi a diverse reti di rilevazione mondiale di eventi sismici.
In prima istanza Botquake invierà una breve presentazione e una lista di comandi con il quale l’Utente potrà comunicare con la macchina sul quale Botquake è in esecuzione e richiedere i dati ai quali è interessato, in particolare potrà richiedere i dati sull'ultimo terremoto avvenuto nell'area di interesse.
Per il nostro scopo restringeremo la zona di interesse all'area Etnea, facendo una prima scrematura dei dati estrapolati direttamente sulla macchina dove è eseguito Botquake. 
L’Utente potrà inviare una richiesta relativa all’ultimo terremoto registrato, alla richiesta Botquake risponderà con i dati dell'ultimo terremoto relativo al comando inviato.
Inoltre, l’Utente potrà affinare la ricerca con un apposito comando impostando una magnitudine massima di interesse, il Botquake risponderà inviando i dati relativi all’ultimo evento sismico al di sotto la magnitudine massima impostata.
Seguirà una mappa relativa al luogo dell'evento con il grado di magnitudine dell'evento sismico rilevato.

Team di sviluppo

- @linuchs
- @lorenzodidomenic

**Link della repository del progetto :** 
https://github.com/linuchs/Botquake

**Comment by simone989** [comment]
Ciao Ragazzi, il Dott Borzì mi ha assegnato la Code Review del vostro progetto.
Ho già messo il vostro progetto in watch, non appena aprirete delle pull request sarà mio compito revisionare il codice e fornirvi dei feedback su quanto fatto.

Buona domenica

**Comment by linuchs** [comment]
> Ciao Ragazzi, il Dott Borzì mi ha assegnato la Code Review del vostro progetto. Ho già messo il vostro progetto in watch, non appena aprirete delle pull request sarà mio compito revisionare il codice e fornirvi dei feedback su quanto fatto.
> 
> Buona domenica

Grazie a presto!
