### ISSUE TITLE
🤝 RistoBOT: Da Tony&Ale

### ISSUE THREAD

**Issue by Antonino698** [UNICT-Quality-Development/qd-projects#37]
Progetto universitario di fine seminario “Quality Development” svolto nell’ a.a. 2023/2024.

Nome progetto: **RistoBOT: Da Tony&Ale**.

Scopo: Realizzare un Bot Telegram per la gestione di prenotazioni di tavoli di un Ristorante. 

Descrizione: In questo progetto il bot Telegram consente agli utenti di:

- prenotare tavoli in un ristorante immaginario che ha un massimo di 10 posti a sedere per ogni fascia oraria (attualmente saranno tre: 20:00/21:00/22:00);
- visualizzare e, se lo si vuole, disdire la prenotazione;
- visualizzare il menu;
- visualizzare le informazioni utili quali: mappa, numeri e sito web;
- visualizzare eventi della settimana.

Specifiche Tecniche: realizzato in python con i seguenti comandi:

- **/start** = avvio del bot
- **/prenota** =chiederà all'utente la fascia oraria e il numero di posti da prenotare
- **/le\_mie\_prenotazioni** =permette di visualizzare le prenotazioni attive dell'utente, se ve ne sono e di cancellarle (singolarmente per id, oppure tutte in una volta)
- **/menu** = visualizza il menù.
- **/eventi** =visualizza gli eventi attivi della settimana corrente
- **/info** =visualizza i contatti del ristorante come sopra citato.

È stato, inoltre, realizzato un database di supporto per l’archiviazione dei dati forniti dall’utente e per gestire le prenotazioni dei tavoli.
Le CRUD operation attivano dei trigger per mantenere allineate le informazioni relative alle prenotazioni.

Partecipanti e link del progetto:

\- [XeenAle](https://github.com/XeenAle)

\- [Antonino698](https://github.com/Antonino698)

\- [Link al Repository](<https://github.com/Antonino698/RistoBOT>)

Di seguito i nostri dati:

**Alessandra Di Fiore**

- cod. matricola -> 1000012469 -> username GitHub: XeenAle

**Antonino Cristaldi**

- cod. matricola -> X81000478 -> username GitHub: Antonino698

**NB:**

La Pipeline su GIT -> CI.yml fallisce alla fase pytest, poiché non viene intercettata un’istanza attiva del server MySQL.

Con l’istanza attiva si ottiene una **code coverage dell’85%.**

**Comment by Helias** [comment]
```bash
 # Aggiunto "|| true" per evitare errori non fatali
 ```
 Gli errori di pylint vanno fixati non ignorati con `|| true` se no a cosa serve eseguire pylint?
 
 `La Pipeline su GIT -> CI.yml fallisce alla fase pytest, poiché non viene intercettata un’istanza attiva del server MySQL.`
 Bisogna "mockare" il database,  forse non è una cosa immediate da fare ma bisogna avere una pipeline funzionante, altrimenti è messa lì tanto per, il che è un po' come non averla (soprattutto se si ignora il risultato di pylint o dei test)

**Comment by Helias** [comment]
inoltre, non è necessario scrivere il percorso del file assoluto nella pipeline in base all'environment del code usato nella github action
`pytest --cov src /home/runner/work/RistoBOT/RistoBOT/test/`
ma potete usare un percorso relativo `pytest --cov src test/`

**Comment by Helias** [comment]
Capisco la difficoltà, purtroppo in 3 CFU non ho approfondito tutti i tipi di mock, però basandomi sulle slide di QD del software testing ho fatto una prova al volo per mockare la variabile globale `db` che state utiizzando come database.

Ho modificato [questo test case](https://github.com/Antonino698/RistoBOT/blob/main/test/test_prenota_command.py#L230) in questo modo per non far fallire il test:
```python
@pytest.mark.asyncio
async def test_button_click_date(mocker: MockerFixture, update_context_fixture):
    mocker.patch.object(db, "connect", return_value=True)
    mocker.patch.object(db, "disconnect", return_value=True)
    mocker.patch.object(db, "execute_query", return_value=[{"n_row": 4}])
    mocker.patch.object(db, "select_query", return_value=[{"n_row": 4}])

    update_mock, context_mock, query_mock, bot_mock, db_mock = update_context_fixture

    query_mock.data = "manageDate@2023-01-01"
    update_mock.callback_query = query_mock
    update_mock.effective_chat.id = 123
    context_mock.bot = bot_mock
    context_mock.user_data = {}

    db_mock.select_query.return_value = [{"n_row": 3}]

    result = await button_click(update_mock, context_mock)

    bot_mock.delete_message.assert_called_with(chat_id=query_mock.message.chat_id, message_id=query_mock.message.message_id)
    bot_mock.send_message.assert_called_once_with(chat_id=update_mock.effective_chat.id, text="D'accordo! La data selezionata è 01-01-2023 . Rispondi con un qualsiasi carattere per continuare...")
    assert result == TIME_SLOT
```

Usando la variabile `mocker`, come dalle slide e facendo il mock delle 4 funzioni della classe `MySQLDatabase` potete riuscire a NON far fallire i tests.

Cercate di:
- NON far fallire la pipeline su github
- NON ignorate errori di pylint tranne se proprio non riuscite a fixarli (in quel caso usate `pylint: disable=nome_del_warning` nel codice specifico dove vi dà il warning)
- NON fate fallire i test nella pipeline usando pytest

Ho visto che avete fatto molto nel progetto, anche al livello di tests, cercate di fare queste ultime cose, non dovrebbe essere complicato e dovrebbe richiedere poche ore.

P.S.: vi consiglio di mockare le 4 funzioni della classe MySQLDatabase mediante una funzione che prenda in input i return_value in modo da non dover riscrivere per ogni test mocker.object.patch... ecc.
