### ISSUE TITLE
✅ [2] Text to speech & Albo bot unit-test code coverage 100%

### ISSUE THREAD

**Issue by Helias** [UNICT-Quality-Development/qd-projects#8]
Questo progetto consiste nello sviluppare un programma che permetta di convertire del testo in un file audio sintetizzando una voce che "dice" esattamente ciò che l'utente scrive in input.

Data la semplicità di questo progetto, oltre alla sua implementazione aggiungerei come esercizio di scrivere gli unit-test del progetto [Albo-2-Telegram](https://github.com/UNICT-DMI/albo-2-telegram/) al fine di raggiungere la code-coverage del 100%.

Per verificare la % di code coverage è possibile utilizzare il seguente comando all'interno del progetto:
```bash
$ pytest --cov . tests/ --cov-report=html
```

**Bonus feature:**
- rendere questo progetto un bot di telegram
- supportare più lingue oltre la lingua italiana

---

Il progetto dovrà prevedere una pipeline tramite le GitHub Action e lo sviluppo di unit-test mediante il framework pytest raggiungendo una code coverage del 75%.

---

Questo progetto è stato già assegnato

**Comment by LivioLipani** [comment]
Io è il mio collega vorremo prendere questo progetto, gli username sono LivioLipani e lordGrim2

**Comment by Helias** [comment]
ok, scrivi un email con nome,cognome, matricola e username di github

appena crei la repository, scrivi il link qui

**Comment by LivioLipani** [comment]
LivioLipani.1000001067.LivioLipani@outlook.com

**Comment by Helias** [comment]
@LivioLipani  Scrivi un messaggio di posta elettronica all'indirizzo email stefano.borzi@phd.unict.it con nome,cognome, matricola ed username di github dei membri del team.

Se scrivi su github queste info renderesti pubblica l'associazione matricola - nome cognome, ciò deve essere mantenuto privato

**Comment by LivioLipani** [comment]
La repository la devo fare public o private ?

**Comment by Helias** [comment]
a tua scelta, se la fai private non puoi applicare le regole del branching descritte nelle linee guida, ma queste regole le puoi rispettare lo stesso NON apportando commit nella branch main tranne mediante PR

private o public, scrivi il link qui, se è private ovviamente è necessario aggiungermi per permettermi di visualizzare la repository

**Comment by LivioLipani** [comment]
https://github.com/LivioLipani/git-project-seminario.git
Pero non ho capito come aggiungere una pipeline mediante Github Action.
Ho provato ad aggiungerla ma spuntano diversi framework pytest

**Comment by Helias** [comment]
Durante l'esercitazione di Lunedì 30 Maggio vedremo in aula una repository "template" dove è presente una pipeline

**Comment by LivioLipani** [comment]
Va bene, quindi la lascio cosi ?
